source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DBEmptyState_Example', :exclusive => true do
  pod "DBEmptyState", :path => "../"
end

target 'DBEmptyState_Tests', :exclusive => true do
  pod "DBEmptyState", :path => "../"

  
end
